config/routes.rb
Rails.application.routes.draw do
  get 'home/explore'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'about', to: 'pages#about'
  get 'coin_explore', to: 'pages#explore'
  get 'dashboard', to: 'pages#dashboard'
  get 'coin', to: 'pages#coin'
  get 'watchlist', to: 'watchlists#show'


  resources :users do
    resources :wallets, only: [ :new, :create, :destroy ] do
      # resources :assets, only: [ :create, :destroy ]
    end
  end

  get 'watchlist', to: 'watchlists#show'
  resources :watchlists, only: [:show] do
    resources :coin_bookmarks, only: [:new, :create, :destroy]
  end

  resources :wallets, only: [] do
    resources :assets, only: [ :new, :create,:edit, :update ]
  end
  # resources :strategys, only: [] do
  #   resources :coin_shares, only: [:index, :create]
  # end
  # resources :coin_shares, only: [:update, :destroy]

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  has_many :coin_bookmarks, dependent: :destroy
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController

  def show
    @tickers = generate_tickers
    @data = call_coin_gecko
    @coin_bookmark = CoinBookmark.new
    authorize @watchlist
  end

  def explore
    @top10 = call_coin_gecko[0..9]
    url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd'
    if params[:query].present?
      data = HTTParty.get(url).body
      data_json = JSON.parse(data)
      if data_json.select{ |key| key["symbol"] == params[:query] }.empty?
        flash[:alert] = "This coin doesn't exist, type again."
      else
        response = data_json.select{ |key| key["symbol"] == params[:query] }.first
        @coin = response.transform_keys(&:to_sym)
        @btc = get_btc
      end
    end
  end

  def coin

    url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd'
    if params[:query].present?
      data = HTTParty.get(url).body
      data_json = JSON.parse(data)
      query = params[:query].present? ? params[:query].downcase : params[:query]
      id_query = data_json.select{ |key| key["symbol"].downcase == query || key["name"].downcase == query}
      if id_query.empty? || query.blank?
        redirect_to coin_explore_path
        flash[:alert] = "This coin doesn't exist, type again."
      else
        @coin = get_coin(id_query)
      end
    else
      redirect_to coin_explore_path
    end

  end

  private

  def generate_tickers
    @watchlist = Watchlist.where(user: current_user)[0]
    @watchlist.coin_bookmarks.pluck(:coin_ticker).map{|coin| "#{coin}" }
  end

  def call_coin_gecko
    url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd'
    data = HTTParty.get(url).body
    JSON.parse(data)
  end
end

app/views/watchlists/show.html.erb
<section class="section dashboard p-0">

  <div class="row">

    <!-- Left Side -->
    <div class="col-8">

      <div class="card recent-sales">

        <div class="card-body">

          <h5 class="card-title"> Coins <span>| watchlist</span></h5>

          <table id="table" class="table table-borderless datatable">

            <thead>

              <tr>
                <th scope="col">Ticker</th>
                <th scope="col">Coin</th>
                <th scope="col">Market Cap</th>
                <th scope="col">Curren Price</th>
                <th scope="col">24H Change</th>
              </tr>

            </thead>
            <tbody>

              <% @tickers.each do |ticker| %>

                <% coin = @data.select{ |key| key["symbol"].downcase == ticker || key["name"].downcase == ticker}.first.transform_keys(&:to_sym) %>
                <tr class='handle'>
                  <th scope="row"><%= coin[:symbol].upcase %></th>
                  <td><a href="/coin?query=<%= coin[:name] %>"><%= coin[:name] %></a></td>
                  <td>$<%= number_with_delimiter(coin[:market_cap].round(2), :delimiter => ',') %></td>
                  <td>$<%= number_with_delimiter(coin[:current_price].round(2), :delimiter => ',') %></td>
                  <td style="color: <%= colorful_percentage(coin[:price_change_percentage_24h])%>"><%= coin[:price_change_percentage_24h].round(2) %>%</td>
                </tr>

              <% end %>
            </tbody>

          </table>

        </div>

      </div>

    </div>
    <!-- End Left Side -->

    <!-- Right Side -->
    <div class="col-4">

      <div class="card">

        <div class="card-body">

          <h5 class="card-title"> Add Coin <span>| to watchlist</span></h5>

            <%= simple_form_for [@watchlist, @coin_bookmark] do |f| %>

              <%= f.input :coin_ticker %>
              <%= f.submit %>

            <% end %>

        </div>

      </div>

    </div>
    <!-- End Right Side -->

  </div>

</section>

<%# <%= link_to 'Add coins', new_watchlist_coin_bookmark_path(@watchlist), class: 'btn btn-secondary' %>
<%# <%= link_to '🗑️', watchlist_coin_bookmark_path(@watchlist, ticker), method: :delete %>