config/routes.rb
Rails.application.routes.draw do
  get 'home/explore'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'about', to: 'pages#about'
  get 'coin_explore', to: 'pages#explore'
  get 'dashboard', to: 'pages#dashboard'
  get 'coin', to: 'pages#coin'
  get 'watchlist', to: 'watchlists#show'


  resources :users do
    resources :wallets, only: [ :new, :create, :destroy ] do
      # resources :assets, only: [ :create, :destroy ]
    end
  end

  get 'watchlist', to: 'watchlists#show'
  resources :watchlists, only: [:show] do
    resources :coin_bookmarks, only: [:new, :create, :destroy]
  end

  resources :wallets, only: [] do
    resources :assets, only: [ :new, :create,:edit, :update ]
  end
  # resources :strategys, only: [] do
  #   resources :coin_shares, only: [:index, :create]
  # end
  # resources :coin_shares, only: [:update, :destroy]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-home">
  <div class="container">
    <div class="d-flex justify-content-around align-items-center">
      <div class="col-lg-4 mt-2 mt-lg-0">
        <div id="map"
          style="width: 50%; height: 150px; margin: 10px auto; overflow: hidden;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
        <div class="info-box t-2">
          <h3><i class="fas fa-map-marked-alt"></i>  Address</h3>
          </p>Al Badaa Street,<br>
            Dubai, Nº 5322</p>
        </div>
      </div>
      <div class="col-lg-4 mt-4 mt-lg-0">
        <div class="links">
          <a href="#"><i class="fab fa-github-square"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
        </div>

        <p><i class="fas fa-mobile-alt"></i><strong> Call Us</strong><br>+1 5589 55488 55 </p>
        <p><i class="far fa-envelope"></i><strong> Email Us</strong><br>contact@example.com </p>
        <div class="icon">
          <p>This website was coded with Ruby <i class="fas fa-gem"></i> technology.</p>
        </div>
      </div>
    </div>
    <div class="rigths">
      <p>© 2021 EASYFOLIO All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar_home.html.erb
<div class="navbar-home navbar-light ">
    <% if user_signed_in?  %>
      <%= link_to "#", class: "navbar-brand" do %>
      <span href="#"><i class="fas fa-home"></i></span>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add photo", "#", class: "dropdown-item" %>
            <%= link_to "Profile", "#", class: "dropdown-item" %>
          </div>
        </div>

        <div class="nav-item active">
          <%= link_to "Dashboard", "#_path", class: "nav-link" %>
          <%= link_to "Explore Coins", "#_path", class: "nav-link" %>
          <%= link_to "Wallets", "#wallet_path", class: "nav-link" %>
          <%= link_to "Watch list", "#watchlists_path", class: "nav-link" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </div>
      </div>
    <% else %>
      <li class="btn btn-home">
        <%= link_to "Login", new_user_session_path, class: "btn btn-home mr-auto" %>
        <%= link_to "Sing up", new_user_registration_path, class: "btn btn-home mr-auto" %>
      </li>
    <% end %>
  </div>
</div>