config/routes.rb
Rails.application.routes.draw do
  get 'home/explore'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'about', to: 'pages#about'
  get 'coin_explore', to: 'pages#explore'
  get 'dashboard', to: 'pages#dashboard'
  get 'coin', to: 'pages#coin'
  get 'watchlist', to: 'watchlists#show'


  resources :users do
    resources :wallets, only: [ :new, :create, :destroy ] do
      # resources :assets, only: [ :create, :destroy ]
    end
  end

  get 'watchlist', to: 'watchlists#show'
  resources :watchlists, only: [:show] do
    resources :coin_bookmarks, only: [:new, :create, :destroy]
  end

  resources :wallets, only: [] do
    resources :assets, only: [ :new, :create,:edit, :update ]
  end
  # resources :strategys, only: [] do
  #   resources :coin_shares, only: [:index, :create]
  # end
  # resources :coin_shares, only: [:update, :destroy]

end

app/views/pages/coin.html.erb
<section class="section dashboard p-0">


  <div class="row">

    <a class="mb-4" style="text-decoration: none" href="/coin_explore">< Back to Coin Explore</a>

    <!-- Left side columns -->
    <div class="col-8">

      <div class="row">

        <!-- Coin Card -->
        <div class="col-xxl-4">

          <div class="card info-card" style="height: 172.59px">

            <div class="card-body">

               <h5 class="mr-3 text-end">#<%= @coin['market_cap_rank'] %></h5>


              <div class="d-flex align-items-center mt-1">

                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">

                  <img src="<%= @coin['image']['small'] %>" alt="">

                </div>

                <div class="ps-3">

                  <h6> <%= @coin['name'] %> </h6>
                  <h5 class="m-0" id="chartticker"><%= @coin['symbol'].upcase %></h5>


                </div>

              </div>

              <div class="d-flex justify-content-between">

                <a id ="link" class="m-2" target="_blank" href="<%= @coin['links']['homepage'][0] %>">
                  <span><%= @coin['links']['homepage'][0] %></span>
                </a>


              </div>




            </div>

          </div>

        </div>
        <!-- End Coin Card -->

        <!-- Market Info Card -->
        <div class="col-xxl-8">
          <div class="card info-card sales-card" style="height: 172.59px">

            <div class="card-body price">

              <div class="price-info">

                <p>Current Price:</p>
                <h2>$<%= number_with_delimiter(@coin['market_data']['current_price']['usd'], :delimiter => ',') %></h2>
                <div class="d-flex align-items-center justify-content-end">
                  <p class="mr-2">(24h)</p>
                  <div class="percentage" style="background-color:<%= colorful_percentage(@coin['market_data']['price_change_percentage_24h']) %>">
                    <div class="d-flex align-items-center">
                      <i class="<%= arrow_up_or_down(@coin['market_data']['price_change_percentage_24h']) %>"></i>
                      <p><%= @coin['market_data']['price_change_percentage_24h'].round(2) %>%</p>
                    </div>
                  </div>
                </div>

              </div>

              <div class="price-info wide">

                <div style="width: 45%; padding-right: 20px">
                  <p>Market Cap:</p>

                  <div class="d-flex justify-content-end mb-2 mt-1">
                    <p class="black">$<%= number_with_delimiter(@coin['market_data']['market_cap']['usd'], :delimiter => ',') %></p>
                  </div>
                  <div>
                    <p>Volume:</p>
                    <div class="d-flex justify-content-end mb-2 mt-1">
                      <p class="black">$<%= number_with_delimiter(@coin['market_data']['total_volume']['usd'], :delimiter => ',') %></p>
                    </div>
                  </div>
                </div>

                <div style="width: 45%; padding-right: 20px">
                  <p>All Time High:</p>
                  <div class="d-flex mb-2 mt-1 justify-content-end">
                    <p class="black">$<%= number_with_delimiter(@coin['market_data']['ath']['usd'], :delimiter => ',') %></p>
                  </div>
                  <div class="d-flex justify-content-end mb-2 mt-1">
                    <div class="dropdown mt-3">
                      <a id="trade-btn" class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        Trade Now
                      </a>

                      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="#">Binance</a></li>
                        <li><a class="dropdown-item" href="#">FTX</a></li>
                        <li><a class="dropdown-item" href="#">Coin Base</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>

        </div>
        <!-- End Market Info Card -->

      </div>

      <!-- TV Chart -->
      <div class="card">

        <div class="card-body">

          <div class="tradingview-widget-container" id="tvchart"></div>

        </div>

      </div>
      <!-- End TV Chart -->

    </div>

    <!-- End Left side columns -->

    <!-- Right side columns -->
    <div class="col-4">

      <!-- TradingView Widget BEGIN -->
      <div class="card">

        <div class="card-body">

          <div class="tradingview-widget-container" style="margin: 0 auto">
            <div class="tradingview-widget-container__widget"></div>
            <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-technical-analysis.js" async>
            {
            "interval": "1D",
            "width": "90%",
            "isTransparent": true,
            "height": "450",
            "symbol": "BINANCE:<%= @coin['symbol'] %>USD",
            "showIntervalTabs": true,
            "locale": "en",
            "colorTheme": "light"
            }
            </script>
          </div>

        </div>

      </div>
      <!-- TradingView Widget END -->

      <!-- About Card -->
      <div class="card">

        <div class="card-body">

          <h5 class="card-title">About</h5>
          <p>
            <%= @coin['description']['en'][0..700] %>
          </p>
          <a href="">more</a>

        </div>

      </div>
      <!-- End About Card -->


    </div>
    <!-- End Right side columns -->
  </div>

</section>

app/views/pages/dashboard.html.erb
<section class="section dashboard p-0">

  <!-- Page Title -->
  <div class="pagetitle">

    <h1>Wallets</h1>

    <nav>

      <ol class="breadcrumb">

          <!-- Wallets - Tabs -->
        <div class="nav nav-tabs" id="nav-tab" role="tablist">

          <% @wallets.each do |wallet| %>
            <button class="<%= wallet == @wallets.first ? "nav-link active" : "nav-link" %>" id="nav-<%= wallet.name %>-tab" data-bs-toggle="tab" data-bs-target="#nav-<%= wallet.name %>" type="button" role="tab" aria-controls="nav-<%= wallet.name %>" aria-selected="true"><%= wallet.name %></button>
          <% end %>

          <%= link_to new_user_wallet_path(current_user) do %>
            <p id="plus">+</p>
          <% end %>

        </div>
        <!-- End - Wallets - Tabs -->

      </ol>

    </nav>

  </div>
  <!-- End Page Title -->

  <div class="row">

    <!-- Left side columns -->
    <div class="col-lg-8">

      <div class="row">

        <div class="col-12">

          <div class="card recent-sales">

            <div class="card-body">

              <div class="d-flex justify-content-between">

                <h5 class="card-title"> Coins <span>| owned</span></h5>

              </div>


              <!-- Wallets - Assets -->
              <div class="tab-content" id="nav-tabContent">
                <% @wallets.each do |wallet| %>
                  <% total = [] %>

                  <div class="<%= wallet == @wallets.first ? "tab-pane fade show active" : "tab-pane fade" %>" id="nav-<%= wallet.name %>" role="tabpanel" aria-labelledby="nav-<%= wallet.name %>-tab">

                    <table class="table table-borderless datatable">

                      <thead>

                        <tr>

                          <th scope="col">#</th>
                          <th scope="col">Coin</th>
                          <th scope="col">Amount</th>
                          <th scope="col">Current Price</th>
                          <th scope="col">Value (U$)</th>
                          <th scope="col">24h</th>
                          <%= link_to new_wallet_asset_path(wallet) do %>
                            <p>add an asset</p>
                          <% end %>

                        </tr>

                      </thead>

                      <tbody>

                        <% assets = wallet.assets %>
                        <% assets.each do |asset| %>
                          <% coin = coin(@data, asset) %>
                          <% total.push((asset.amount*coin[:current_price]).round(2)) %>
                          <tr>

                            <th scope="row"><%= asset.coin_ticker.upcase %></th>
                            <td><a href="/coin?query=<%= coin[:name] %>"><%= coin[:name] %></a></td>
                            <td>
                              <%= asset.amount.round(2) %> |
                              <%= link_to edit_wallet_asset_path(wallet, asset) do%>
                                <i class="fas fa-edit"></i>
                              <% end %>

                            </td>
                            <td>$<%= number_with_delimiter(coin[:current_price].round(2), :delimiter => ',') %></td>
                            <td>$<%= number_with_delimiter((asset.amount.round(2)*coin[:current_price]).round(2), :delimiter => ',') %></td>
                            <td style="color:<%=colorful_percentage(coin[:price_change_percentage_24h])%>"><%= coin[:price_change_percentage_24h].round(2) %>%</td>

                          </tr>
                        <% end %>

                      </tbody>

                    </table>

                    <!-- Total Section -->
                    <div class="d-flex">

                      <!-- Total U$ Section -->
                      <div class="card-body">

                        <h5 class="card-title">Total <span>| USD</span></h5>

                        <div class="d-flex align-items-center">

                          <div class="ps-3">

                            <h6>$<%= number_with_delimiter(total.sum.round(2), :delimiter => ',') %></h6>
                            <span class="text-success small pt-1 fw-bold">12%</span> <span class="text-muted small pt-2 ps-1">increase</span>

                          </div>

                        </div>

                      </div>
                      <!-- End - Total U$ Section -->

                      <!-- Total BTC Section -->
                      <div class="card-body">
                        <h5 class="card-title">Total <span>| BTC</span></h5>

                        <div class="d-flex align-items-center">
                          <div class="ps-3">
                            <% btc = @data.select{ |key| key["symbol"] == 'btc' }.first.transform_keys(&:to_sym) %>
                            <h6><%= (total.sum/btc[:current_price]).round(6) %></h6>
                            <span class="text-success small pt-1 fw-bold">8%</span> <span class="text-muted small pt-2 ps-1">increase</span>

                          </div>
                        </div>
                      </div>
                      <!-- End - Total BTC Section -->

                    </div>
                    <!-- end Total Section -->

                  </div>
                <% end %>

                </div>

              </div>
              <!-- End - Wallets - Assets -->

            </div>

        </div>

      </div>
    </div>
    <!-- End Left side columns -->

    <!-- Right side columns -->
    <div class="col-lg-4">

      <!-- Market Overall -->


      <!-- End Market Overall -->

    </div>
    <!-- End Right side columns -->

  </div>

</section>

app/views/pages/explore.html.erb
<section class="section dashboard p-0">

  <div class="pagetitle">

    <h1>Explore new coins</h1>

  </div><!-- End Page Title -->

  <div class="row">

    <!-- Left side columns -->
    <div class="col-8">

      <div class="card recent-sales">

        <div class="card-body">

          <h5 class="card-title">Top 10 <span>| coins</span></h5>

          <table class="table table-borderless datatable">

            <thead>

              <tr>

                <th scope="col">#</th>
                <th scope="col">Coin</th>
                <th scope="col">Current Price</th>
                <th scope="col">All Time High</th>
                <th scope="col">Market Cap</th>
                <th scope="col">24h (%)</th>

              </tr>

            </thead>

            <tbody>

              <% @top10.each do |coin| %>
                <tr>

                  <th scope="row"><%= coin['market_cap_rank'] %></th>
                  <td><a href="/coin?query=<%= coin['name'] %>"><%= coin['name'] %></a></td>
                  <td>$<%= coin['current_price'] %></td>
                  <td> $<%= number_with_delimiter(coin['ath'].round(2), :delimiter => ',') %> </td>
                  <td>$<%= number_with_delimiter(coin['market_cap'], :delimiter => ',')%></td>
                  <td style="color: <%= colorful_percentage(coin['price_change_percentage_24h'])%>"><%= coin['price_change_percentage_24h'].round(2) %>%</td>

                </tr>
              <% end %>

            </tbody>

          </table>

        </div>

      </div>

    </div>
    <!-- End Left side columns -->

    <!-- Right side columns -->
    <div class="col-4">

      <div class="card recent-sales">

        <div class="card-body">

          <h5 class="card-title"> Coin <span>| Explore</span></h5>
          <%= form_tag coin_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              autocomplete:"off",
              placeholder: "Find a coin",
              id: "find-coin"
            %>
            <ul id="results" class="list-group"></ul>
            <%= submit_tag "Search", class: "btn btn-primary mt-2" %>
          <% end %>
          
        </div>
        <%= render 'shared/flashes' %>
      </div>

    </div>
    <!-- End Right side columns -->

  </div>

</section>