config/routes.rb
Rails.application.routes.draw do
  get 'home/explore'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'about', to: 'pages#about'
  get 'coin_explore', to: 'pages#explore'
  get 'dashboard', to: 'pages#dashboard'
  get 'coin', to: 'pages#coin'
  get 'watchlist', to: 'watchlists#show'


  resources :users do
    resources :wallets, only: [ :new, :create, :destroy ] do
      # resources :assets, only: [ :create, :destroy ]
    end
  end

  get 'watchlist', to: 'watchlists#show'
  resources :watchlists, only: [:show] do
    resources :coin_bookmarks, only: [:new, :create, :destroy]
  end

  resources :wallets, only: [] do
    resources :assets, only: [ :new, :create,:edit, :update ]
  end
  # resources :strategys, only: [] do
  #   resources :coin_shares, only: [:index, :create]
  # end
  # resources :coin_shares, only: [:update, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
    <title>Easyfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-technical-analysis.js" async></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
      <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center p-4 mt-2">
      <%= link_to dashboard_path do %>
        <h1 id="logo">EasyFolio</h1>
      <% end %>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

  </header><!-- End Header -->


  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">


        <li class="nav-item">
          <%# <a class="nav-link " href="dashboard"> %>
          <%= link_to "Dashboard", dashboard_path, class:"nav-link ml-2" %>

        </li><!-- End Dashboard Nav -->


      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" href="coin_explore">
          <i class="bi bi-menu-button-wide"></i><span>Coin Explore</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>

      </li><!-- End Components Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" href="watchlist">
          <i class="bi bi-journal-text"></i><span>Watch List</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
      </li><!-- End Forms Nav -->


      <li class="nav-heading">Pages</li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="pages-blank.html">
          <i class="bi bi-file-earmark"></i>
          <span>Logout</span>
        </a>
      </li><!-- End Blank Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->
  <main id="main" class="main">
    <%= yield %>
  </main>


    <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>EasyFolio</span></strong>. All Rights Reserved
    </div>

  </footer><!-- End Footer -->

  </body>
</html>

app/views/layouts/landingpage.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
    <title>Easyfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>


    <%= render 'shared/flashes' %>
    <%= yield %>
    <!-- <p class="notice"><%#= notice %></p>
         <p class="alert"><%#= alert %></p> -->
  </body>
</html>